apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gp-app-0325
  janus-idp.io/tekton: gp-app-0325
  backstage.io/kubernetes-id: gp-app-0325
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gp-app-0325
resources: 
- deployment.yaml
- route.yaml
- service.yaml
