apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: gp-app-0325
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gp-app-0325 
  name: gp-app-0325
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: gp-app-0325
    weight: 100 
